name: The Web Workers

collections:
    podcast:
        output: true
        permalink: /podcast/:path/

url: http://memphiswebworkers.com/

exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
